### ISSUE TITLE
Permission to contribute valuable content to your project (FAQ, About Us, Contact Us, Privacy Policy)

### ISSUE THREAD

**Issue by RolletOso** [moitto/moitto#1]
Hello, 

The idea of your project is amazing and while you are doing an awesome job with technical aspects and coding, i will like to take some weight off you by offering copywriting services.

I will contribute a privacy policy which is a statement or a legal document that discloses some or all of the ways a party gathers, uses, discloses, and manages a customer or client's data.

I will contribute a compelling About Us content that will tell off your founding story, a content that will show off your the core or your project, and will answer the most pressing question new and old users may have about your project. 

I will also create  FAQ Content. I will use Frequently asked questions or Questions and Answers to list out questions and answers, all supposed to be commonly asked in some context, and pertaining to your project and more insight to the project. 

I will also create an updated version of your ReadMe file. 

I am willing to contribute to the copywriting aspect of your project so you can put more effort on the technicalities and perform at your optimum best. 

Anticipating Your response.

Thank you.

**Comment by hanyeol** [comment]
Thank you for your interest!

I would like to know why you are interested in Moitto project.
Please tell me your opinion about the project.

**Comment by RolletOso** [comment]
Moitto is the future. The idea of coming up with a project like this is
mind-blowing. Why am i saying this, as the world is improving and moving
ahead, people want things to be less hectic and more simple, so if they
have an app that gathers all the apps they need in one place, who wouldn't
go for it. Coupled with the fact that they don't even need to install the
apps to use them, this alone is enough reason for me to love the project.

Doing my own in part is making sure that each and everyday this project is
heading towards perfection will be very fulfilling.

Thanks for swift response.

**Comment by hanyeol** [comment]
Thank you for your reply.

Can you translate Korean text to English one? 
You can use Google Translator, and then refine the text.
If you can, please let me know. 

Also I hope you can run Moitto on your Mac and understand it better.
If you don't use Moitto, you may not be able to write about it.

Thanks.

**Comment by RolletOso** [comment]
Yes i can translate Korean to English so I can comfortably write better and
translate it to Korean if you wish me to. And I'll get Moitto on my Mac to
help me understand it better.

But there are certain details I'll still need to get from you.

Thanks.

**Comment by hanyeol** [comment]
Hello, 

Have you tried to run Moitto on your Mac? 
Please let me know what's your opinion.

Thanks.

**Comment by RolletOso** [comment]
I'm having issues installing it on my Mac

**Comment by hanyeol** [comment]
I'll close this issue.
